apiVersion: v1
kind: Service
metadata:
  name: travelmemory-frontend-service
  namespace: frontend
spec:
  selector:
    app: travelmemory-frontend
  ports:
  - port: 80
    targetPort: 3000
  type: LoadBalancer
