apiVersion: v1
kind: Service
metadata:
  name: travelmemory-backend-service
  namespace: backend
spec:
  selector:
    app: travelmemory-backend # label to match the pods created by the deployment
  # This service will route traffic to the pods created by the deployment
  ports:
  - port: 80
    targetPort: 3001
    nodePort: 30001
    protocol: TCP
  type: NodePort # LoadBalancer 
  