apiVersion: apps/v1
kind: Deployment
metadata:
  name: travelmemory-frontend
  namespace: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: travelmemory-frontend
  template:
    metadata:
      labels:
        app: travelmemory-frontend
    spec:
      initContainers:
      - name: frontend-builder
        image: node:14
        command: ["/bin/bash", "-c"]
        args:
        - |
          echo "Cloning repository..."
          git clone https://github.com/XXRadeonXFX/TravelMemory.git /tmp/repo
          
          echo "Setting up frontend..."
          mkdir -p /build
          cp -r /tmp/repo/frontend/* /app/
          cd /app
          
          echo "Creating .env file..."
          cp /env-config/.env .
          cat .env
          
          echo "Installing dependencies..."
          npm install
          
          echo "Building frontend..."
          npm run build
          
          echo "Copying build files to Nginx directory..."
          cp -r build/* /build/
          
          echo "Frontend build complete!"
        volumeMounts:
        - name: build-volume
          mountPath: /build
        - name: app-volume
          mountPath: /app
        - name: env-config
          mountPath: /env-config
      containers:
      - name: frontend-server
        image: nginx:alpine
        ports:
        - containerPort: 80
        volumeMounts:
        - name: build-volume
          mountPath: /usr/share/nginx/html
        - name: nginx-config
          mountPath: /etc/nginx/conf.d/default.conf
          subPath: nginx.conf
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "200m"
      volumes:
      - name: build-volume
        emptyDir: {}
      - name: app-volume
        emptyDir: {}
      - name: nginx-config
        configMap:
          name: frontend-nginx-conf
      - name: env-config
        configMap:
          name: frontend-env