apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: default
spec:
  selector:
    matchLabels:
      app: ecom-1
  replicas: 2  # tell deployment to run 2 pods matching this template
  template:
    metadata:
      labels:
        app: ecom-1
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80